### ISSUE TITLE
Travis failing on master for 3.8-dev build

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#231]
On the `master` branch, travis is crashing for the 3.8-dev build.

```
Resolving deltas:  99% (1729/1745)   
Resolving deltas: 100% (1745/1745)   
Resolving deltas: 100% (1745/1745), done.
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'
/home/travis/build/LSSTDESC/CLMM
travis_time:end:0cb3abae:start=1581429733887260616,finish=1581429734683802310,duration=796541694,event=install
[0Ktravis_fold:end:install.3
[0Ktravis_fold:start:install.4
[0Ktravis_time:start:0121b258
[0K$ pip install -r requirements.txt
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8-dev/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
travis_time:end:0121b258:start=1581429734688353658,finish=1581429734714544435,duration=26190777,event=install
[0K[31;1mThe command "pip install -r requirements.txt" failed and exited with 1 during .[0m

Your build has been stopped.
```

I suspect that is because 3.8.1 was released mid-December. Should be able to fix by changing the bleeding-edge python version to 3.9-dev.

**Comment by matthewkirby** [comment]
Looking at the travis documentation on the supported python [here](https://docs.travis-ci.com/user/languages/python/#python-versions) I see that 3.8, 3.8.1, 3.8-dev, 3.9-dev should all work.
![image](https://user-images.githubusercontent.com/5395125/74260378-aa1ce280-4cb6-11ea-9b80-b360a6e45e41.png)

However, both 3.8-dev and 3.9-dev both fail with the above error. 3.8.1. works.

**Comment by matthewkirby** [comment]
So as it turns out this problem is being caused by a new release of virtualenv.

https://travis-ci.community/t/python-development-versions-no-longer-include-pip/7180/5

We are still installing 3.8-dev but the dev environments no longer contain pip (because of this bug).

The solution might just be to wait it out.

**Comment by matthewkirby** [comment]
I am going to close this issue, I expect that it will be fixed by the end of the day. The problem is on travis' end not ours.

I did update `3.8-dev` to `nightly` so I am going to open a PR for that.
